## Блок 1

#### 1.

Как выйти из вим? Этот вопрос однажды стал самым популярный на сайте stackoverflow и о нем даже написал сайт meduza. Сегодня вы узнаете еще один способ (хотя, конечно, зажать кнопку питания на 5 секунд все еще самый надежный). Откройте вим командой vim, и далее попробуйте приостановить программу, так, как мы это делали на уроке. Далее вам остается только завершить приостановленный процесс. Ну или продолжить программу.

#### 2.

Как мы с вами говорили в разборе домашней работы, у функции subprocess.run есть еще один опциональный аргумент – encoding. Если его передать, и указать нужную нам кодировку, например `encoding=”utf8”`, то помимо декодирования аутпута от процесса, мы теперь можем передать в функцию аргументом input строку. Потренируйтесь с запуском таких программ, добавив в нашу тестовую программу еще несколько вызовов функции input


## Блок 2


#### 1.

Еще одна консольная утилита, которой вам предстоит много пользоваться – `lsof`. Эта команда может вам рассказать очень много интересного о файлах в системе. Где-нибудь впереди мы ее обязательно изучим, но пока что нам нужна лишь одна из ее возможностей – найти процесс по занятому им порту.

Запуск:
 `lsof -i :port` даст нам строку, где будет указан PID процесса, который занял нужный нам порт. Например, `lsof -i :500`
 
Это была фабула, а теперь задание. Мы уже видели, что наш сервер на фласке отказывается запускаться, если кто-то занял его порт. Непорядок!  Напишите функцию, которая будет запускать фласк сервер (любой) по переданному в нее порту, и, если порт будет занят – найдет процесс по этому порту, завершит его, и попытается запустить сервер еще раз.
Чтобы завершить процесс, можно воспользоваться функцией `os.kill()` из стандартной библиотеки os https://docs.python.org/3.8/library/os.html#os.kill

#### 2.

Почему бы вместо того, чтобы везде писать try … except блоки, не начать использовать протоколы контекстного менеджера?
Реализуйте такой контекстный менеджер, что он принимает в `__init__` кортеж типов исключений  и если они выскочат внутри блока with – то проигнорирует их, а если такой тип исключения не ожидается – то прокинет его выше. Подумайте, как будут работать вложенные блоки.
 
Тесты к заданию – обязательны!


## Блок 3
 
#### 1.

Иногда у нас может возникнуть необходимость перенаправить аутпут от программы в нужное нам место в “runtime”, то есть изнутри самой программы. Напишите такой менеджер контекста, что в `__init__` он принимает IO object для stdout и stderr (например, открытый файл). Теперь все, чтобы ни писалось в эти потоки 1, 2 (print, raised exceptions) внутри блока with должно попадать в эти объекты. Не забудьте проверить вложенные блоки with.

Подсказка: дефолтные значения для потоков должны быть sys.stderr, sys.stdout
 
Тесты к заданию – обязательны.
